# Website www.seguridadwireless.es container
# author: Adrian Campos <adriancampos@teachelp.com>

FROM centos:8
MAINTAINER Alenode <adriancampos@teachelp.com>

RUN yum -y install nginx && \
    yum clean all && \
    mkdir -p /var/www/html

COPY ./container/nginx.conf /etc/nginx/nginx.conf
COPY ./images /var/www/html/
COPY ./webpage/* /var/www/html/
COPY ./dist /var/www/html/

EXPOSE 80

#USER nginx

CMD ["nginx","-g","daemon off;"]
