# Website www.seguridadwireless.es container
# author: Adrian Campos <adriancampos@teachelp.com>

FROM registry.alefnode.com/centos:8
MAINTAINER Alenode <adriancampos@teachelp.com>

RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum -y install nginx && \
    yum clean all && \
    mkdir -p /var/www/html

RUN mkdir -p /var/www/html/images && \
    mkdir -p /var/www/html/dist

COPY ./container/nginx.conf /etc/nginx/nginx.conf
COPY ./images/* /var/www/html/images/
COPY ./webpage/* /var/www/html/
COPY ./dist/* /var/www/html/dist/

EXPOSE 80

#USER nginx

CMD ["nginx","-g","daemon off;"]
